/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week12;

import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeParseException;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ecliptica
 */
public class Quiz2 extends javax.swing.JFrame {

    /**
     * Creates new form BiodataFrame
     */
    public Quiz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        genderGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nikText = new javax.swing.JTextField();
        namaText = new javax.swing.JTextField();
        pendidikanComboBox = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        bacaCheckBox = new javax.swing.JCheckBox();
        makanCheckBox = new javax.swing.JCheckBox();
        tidurCheckBox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatText = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        noTelpText = new javax.swing.JTextField();
        tanggalLahirText = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ipkText = new javax.swing.JFormattedTextField();
        resetButton = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        keluarMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        jLabel3.setText("Pendidikan");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Hobi");

        jLabel6.setText("Alamat");

        pendidikanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "SD", "SMP", "SMA", "D1", "D2", "D3", "D4 / S1", "S2", "S3" }));
        pendidikanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendidikanComboBoxActionPerformed(evt);
            }
        });

        genderGroup.add(jRadioButton1);
        jRadioButton1.setText("Laki-laki");

        genderGroup.add(jRadioButton2);
        jRadioButton2.setText("Perempuan");

        bacaCheckBox.setText("Membaca");

        makanCheckBox.setText("Makan");

        tidurCheckBox.setText("Tidur");
        tidurCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidurCheckBoxActionPerformed(evt);
            }
        });

        alamatText.setColumns(20);
        alamatText.setRows(5);
        jScrollPane2.setViewportView(alamatText);

        okButton.setText("Daftar");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Nomor Telepon");

        tanggalLahirText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalLahirTextActionPerformed(evt);
            }
        });

        jLabel8.setText("Tanggal Lahir");

        jLabel9.setText("IPK");

        ipkText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipkTextActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        keluarMenu.setText("Keluar");

        jMenuItem1.setText("Keluar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        keluarMenu.add(jMenuItem1);

        jMenuBar2.add(keluarMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(noTelpText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalLahirText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pendidikanComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bacaCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(makanCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tidurCheckBox)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ipkText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(namaText))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bacaCheckBox)
                        .addComponent(makanCheckBox)
                        .addComponent(tidurCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTelpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggalLahirText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pendidikanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ipkText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(resetButton))
                .addGap(25, 25, 25))
        );

        jRadioButton1.setActionCommand("Laki-laki");
        jRadioButton2.setActionCommand("Perempuan");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tidurCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidurCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidurCheckBoxActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();

        // Validasi NIK
        if (nikText.getText().equals("")) {
            sb.append("NIK harus diisi!\n");
        } else {
            sb.append("NIK: ").append(nikText.getText()).append("\n");
        }

        // Validasi Nama
        if (namaText.getText().equals("")) {
            sb.append("Nama harus diisi!\n");
        } else {
            sb.append("Nama: ").append(namaText.getText()).append("\n");
        }

        // Validasi Alamat
        if (alamatText.getText().equals("")) {
            sb.append("Alamat harus diisi!\n");
        } else {
            sb.append("Alamat: ").append(alamatText.getText()).append("\n");
        }

        // Validasi Jenis Kelamin
        ButtonModel genderModel = genderGroup.getSelection();
        if (genderModel == null || genderModel.getActionCommand().isEmpty()) {
            sb.append("Jenis Kelamin harus diisi!\n");
        } else {
            sb.append("Jenis Kelamin: ").append(genderModel.getActionCommand()).append("\n");
        }    

        // Validasi Hobi
        sb.append("Hobi: \n");
        if (bacaCheckBox.isSelected()) {
            sb.append("- ").append(bacaCheckBox.getText()).append("\n");
        }
        if (makanCheckBox.isSelected()) {
            sb.append("- ").append(makanCheckBox.getText()).append("\n");
        }
        if (tidurCheckBox.isSelected()) {
            sb.append("- ").append(tidurCheckBox.getText()).append("\n");
        }

        // Validasi No Telp
        try {
            Long.parseLong(noTelpText.getText());
            sb.append("No Telp: ").append(noTelpText.getText()).append("\n");
        } catch (NumberFormatException e) {
            sb.append("No Telp tidak valid (hanya boleh angka)!\n");
        }

        // Validasi Tanggal Lahir
        try {
            LocalDate tanggalLahir = LocalDate.parse(tanggalLahirText.getText());
            int usia = Period.between(tanggalLahir, LocalDate.now()).getYears();
            if (usia < 18) {
                sb.append("Anda belum cukup umur untuk melamar pekerjaan ini.\n");
            } else {
                sb.append("Tanggal Lahir: ").append(tanggalLahir).append(" (Usia: ").append(usia).append(" tahun)\n");
            }
        } catch (DateTimeParseException e) {
            sb.append("Format Tanggal Lahir tidak valid!\n");
        }

        // Validasi Pendidikan
        Object pendidikanItem = pendidikanComboBox.getSelectedItem();
        if (pendidikanItem == null || pendidikanItem.equals("")) {
            sb.append("Pendidikan harus diisi!\n");
        } else {
            String pendidikan = pendidikanItem.toString();
            sb.append("Pendidikan: ").append(pendidikan).append("\n");
            if (pendidikan.equals("SD") || pendidikan.equals("SMP") || pendidikan.equals("SMA")) {
                sb.append("Minimal pendidikan D1 untuk melamar pekerjaan ini.\n");
            }
        }

        // Validasi IPK
        try {
            double ipk = Double.parseDouble(ipkText.getText());
            if (ipk < 0.00 || ipk > 4.00) {
                sb.append("IPK tidak valid!\n");
            } else if (ipk < 3.01) {
                sb.append("Minimal IPK 3.01 untuk melamar pekerjaan ini.\n");
            } else {
                sb.append("IPK: ").append(ipk).append("\n");
            }
        } catch (NumberFormatException e) {
            sb.append("Format IPK tidak valid!\n");
        }

        // Pesan sukses atau error
        if (sb.toString().contains("harus diisi") || sb.toString().contains("tidak valid") || sb.toString().contains("Minimal")) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Anda berhasil mendaftar", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            // Mengosongkan form
            nikText.setText("");
            namaText.setText("");
            alamatText.setText("");
            genderGroup.clearSelection();
            bacaCheckBox.setSelected(false);
            makanCheckBox.setSelected(false);
            tidurCheckBox.setSelected(false);
            noTelpText.setText("");
            tanggalLahirText.setText("");
            pendidikanComboBox.setSelectedIndex(0);
            ipkText.setText("");
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Object[] options = {"Ya", "Tidak"};
        int result = JOptionPane.showOptionDialog(
            this,
            "Apakah anda ingin keluar?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,
            options[1]
        );
        if (result == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void pendidikanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendidikanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendidikanComboBoxActionPerformed

    private void tanggalLahirTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalLahirTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalLahirTextActionPerformed

    private void ipkTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipkTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipkTextActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        nikText.setText("");
        namaText.setText("");
        alamatText.setText("");
        noTelpText.setText("");
        ipkText.setText("");
        tanggalLahirText.setText("");

        // Set ulang pilihan pada JRadioButton (Jenis Kelamin)
        genderGroup.clearSelection();

        // Hapus centang pada JCheckBox (Hobi)
        bacaCheckBox.setSelected(false);
        makanCheckBox.setSelected(false);
        tidurCheckBox.setSelected(false);

        // Set pilihan default pada JComboBox (Pendidikan)
        pendidikanComboBox.setSelectedIndex(-1); // Atur ke -1 jika tidak ada pilihan default

        JOptionPane.showMessageDialog(this, "Form telah direset", "Reset", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatText;
    private javax.swing.JCheckBox bacaCheckBox;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JFormattedTextField ipkText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenu keluarMenu;
    private javax.swing.JCheckBox makanCheckBox;
    private javax.swing.JTextField namaText;
    private javax.swing.JTextField nikText;
    private javax.swing.JTextField noTelpText;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> pendidikanComboBox;
    private javax.swing.JButton resetButton;
    private javax.swing.JFormattedTextField tanggalLahirText;
    private javax.swing.JCheckBox tidurCheckBox;
    // End of variables declaration//GEN-END:variables
}
